# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sarahkitty/Code/C++/Snake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sarahkitty/Code/C++/Snake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sarahkitty/Code/C++/Snake/CMakeFiles /home/sarahkitty/Code/C++/Snake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sarahkitty/Code/C++/Snake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named a.out

# Build rule for target.
a.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a.out
.PHONY : a.out

# fast build rule for target.
a.out/fast:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/build
.PHONY : a.out/fast

include/imgui-sfml/imgui-SFML.o: include/imgui-sfml/imgui-SFML.cpp.o

.PHONY : include/imgui-sfml/imgui-SFML.o

# target to build an object file
include/imgui-sfml/imgui-SFML.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui-sfml/imgui-SFML.cpp.o
.PHONY : include/imgui-sfml/imgui-SFML.cpp.o

include/imgui-sfml/imgui-SFML.i: include/imgui-sfml/imgui-SFML.cpp.i

.PHONY : include/imgui-sfml/imgui-SFML.i

# target to preprocess a source file
include/imgui-sfml/imgui-SFML.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui-sfml/imgui-SFML.cpp.i
.PHONY : include/imgui-sfml/imgui-SFML.cpp.i

include/imgui-sfml/imgui-SFML.s: include/imgui-sfml/imgui-SFML.cpp.s

.PHONY : include/imgui-sfml/imgui-SFML.s

# target to generate assembly for a file
include/imgui-sfml/imgui-SFML.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui-sfml/imgui-SFML.cpp.s
.PHONY : include/imgui-sfml/imgui-SFML.cpp.s

include/imgui/imgui.o: include/imgui/imgui.cpp.o

.PHONY : include/imgui/imgui.o

# target to build an object file
include/imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.cpp.o

include/imgui/imgui.i: include/imgui/imgui.cpp.i

.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s

.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.o: include/imgui/imgui_demo.cpp.o

.PHONY : include/imgui/imgui_demo.o

# target to build an object file
include/imgui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.cpp.o

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i

.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s

.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.o: include/imgui/imgui_draw.cpp.o

.PHONY : include/imgui/imgui_draw.o

# target to build an object file
include/imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.cpp.o

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i

.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s

.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_widgets.o: include/imgui/imgui_widgets.cpp.o

.PHONY : include/imgui/imgui_widgets.o

# target to build an object file
include/imgui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.cpp.o

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i

.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s

.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

src/Head.o: src/Head.cpp.o

.PHONY : src/Head.o

# target to build an object file
src/Head.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Head.cpp.o
.PHONY : src/Head.cpp.o

src/Head.i: src/Head.cpp.i

.PHONY : src/Head.i

# target to preprocess a source file
src/Head.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Head.cpp.i
.PHONY : src/Head.cpp.i

src/Head.s: src/Head.cpp.s

.PHONY : src/Head.s

# target to generate assembly for a file
src/Head.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Head.cpp.s
.PHONY : src/Head.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/Question.o: src/Question.cpp.o

.PHONY : src/Question.o

# target to build an object file
src/Question.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Question.cpp.o
.PHONY : src/Question.cpp.o

src/Question.i: src/Question.cpp.i

.PHONY : src/Question.i

# target to preprocess a source file
src/Question.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Question.cpp.i
.PHONY : src/Question.cpp.i

src/Question.s: src/Question.cpp.s

.PHONY : src/Question.s

# target to generate assembly for a file
src/Question.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Question.cpp.s
.PHONY : src/Question.cpp.s

src/QuestionManager.o: src/QuestionManager.cpp.o

.PHONY : src/QuestionManager.o

# target to build an object file
src/QuestionManager.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/QuestionManager.cpp.o
.PHONY : src/QuestionManager.cpp.o

src/QuestionManager.i: src/QuestionManager.cpp.i

.PHONY : src/QuestionManager.i

# target to preprocess a source file
src/QuestionManager.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/QuestionManager.cpp.i
.PHONY : src/QuestionManager.cpp.i

src/QuestionManager.s: src/QuestionManager.cpp.s

.PHONY : src/QuestionManager.s

# target to generate assembly for a file
src/QuestionManager.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/QuestionManager.cpp.s
.PHONY : src/QuestionManager.cpp.s

src/Tail.o: src/Tail.cpp.o

.PHONY : src/Tail.o

# target to build an object file
src/Tail.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Tail.cpp.o
.PHONY : src/Tail.cpp.o

src/Tail.i: src/Tail.cpp.i

.PHONY : src/Tail.i

# target to preprocess a source file
src/Tail.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Tail.cpp.i
.PHONY : src/Tail.cpp.i

src/Tail.s: src/Tail.cpp.s

.PHONY : src/Tail.s

# target to generate assembly for a file
src/Tail.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/Tail.cpp.s
.PHONY : src/Tail.cpp.s

src/snake.o: src/snake.cpp.o

.PHONY : src/snake.o

# target to build an object file
src/snake.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/snake.cpp.o
.PHONY : src/snake.cpp.o

src/snake.i: src/snake.cpp.i

.PHONY : src/snake.i

# target to preprocess a source file
src/snake.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/snake.cpp.i
.PHONY : src/snake.cpp.i

src/snake.s: src/snake.cpp.s

.PHONY : src/snake.s

# target to generate assembly for a file
src/snake.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/snake.cpp.s
.PHONY : src/snake.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... a.out"
	@echo "... edit_cache"
	@echo "... include/imgui-sfml/imgui-SFML.o"
	@echo "... include/imgui-sfml/imgui-SFML.i"
	@echo "... include/imgui-sfml/imgui-SFML.s"
	@echo "... include/imgui/imgui.o"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_demo.o"
	@echo "... include/imgui/imgui_demo.i"
	@echo "... include/imgui/imgui_demo.s"
	@echo "... include/imgui/imgui_draw.o"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_widgets.o"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
	@echo "... src/Head.o"
	@echo "... src/Head.i"
	@echo "... src/Head.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Question.o"
	@echo "... src/Question.i"
	@echo "... src/Question.s"
	@echo "... src/QuestionManager.o"
	@echo "... src/QuestionManager.i"
	@echo "... src/QuestionManager.s"
	@echo "... src/Tail.o"
	@echo "... src/Tail.i"
	@echo "... src/Tail.s"
	@echo "... src/snake.o"
	@echo "... src/snake.i"
	@echo "... src/snake.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

